colors.draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x969896"
blue = "0xb4b7b4"
cyan = "0x3971ed"
green = "0x282a2e"
magenta = "0xe0e0e0"
red = "0xf96a38"
white = "0xffffff"
yellow = "0x373b41"

[colors.cursor]
cursor = "0xc5c8c6"
text = "0x1d1f21"

[colors.normal]
black = "0x111111"
blue = "0x81a2be"
cyan = "0x8abeb7"
green = "0x99cc99"
magenta = "0xfef601"
red = "0xcc6666"
white = "0xe0e0e0"
yellow = "0xf8fe7a"

[colors.primary]
background = "0x111111"
foreground = "0xc5c8c6"

[env]
TERM = "alacritty"

[font]
size = 11

[font.bold]
family = "SauceCodePro Nerd Font Mono"
style = "Regular"

[font.bold_italic]
family = "SauceCodePro Nerd Font Mono"
style = "Regular"

[font.italic]
family = "SauceCodePro Nerd Font Mono"
style = "Regular"

[font.normal]
family = "SauceCodePro Nerd Font Mono"
style = "Regular"
